export const LOADING_USER_INFO = "[USER] LOADING_INFO";
export const LOADING_USER_INFO_FULFILLED = "[USER] LOADING_INFO_FULFILLED";
export const LOADING_USER_INFO_FAILED = "[USER] LOADING_INFO_FAILED";

export const LOADING_USER_INFO_STORAGE = "[USER] LOADING_USER_INFO_STORAGE";
export const LOADING_USER_INFO_STORAGE_FULFILLED = "[USER] LOADING_USER_INFO_STORAGE_FULFILLED";
export const LOADING_USER_INFO_STORAGE_FAILED = "[USER] LOADING_USER_INFO_STORAGE_FAILED";

export const ADD_USER_INFO_GOOGLE = "[USER] ADD_USER_INFO_GOOGLE";

export const RESET_LOADING = "[USER] RESET_LOADING"
export const RESET_LOADING_STORAGE = "[USER] RESET_LOADING_STORAGE"